services:
#  postgres:
#    container_name: postgresql
#    image: postgres
#    ports:
#      - "9999:5432"
#    volumes:
#      - pgdata:/var/lib/postgresql
#    environment:
#      POSTGRES_USER: user
#      POSTGRES_PASSWORD: pass
#      POSTGRES_DB: vibe_coding_db
#    networks:
#      - microservices-net
#    restart: unless-stopped

  postgres-vector:
    image: pgvector/pgvector:pg18
    container_name: pgvector-db-lovable
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: vibe_coding_db
    ports:
      - "9010:5432"
    volumes:
      - pgvector-data:/var/lib/postgresql
    networks:
      - microservices-net
    restart: unless-stopped

  minio:
    image: quay.io/minio/minio:latest
    container_name: minio-lovable
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    ports:
      - "9000:9000"    # API
      - "9001:9001"    # Console
    volumes:
      - minio-data:/data
    networks:
      - microservices-net
    restart: unless-stopped

networks:
  microservices-net:
    driver: bridge

volumes:
#  pgdata:
  minio-data:
  pgvector-data:
