spring:
  application:
    name: vibeCoding
    description: This is a Vibe Coding Platform similar to Lovable, Replit etc.

# PostgreSql Database Configurations:
  datasource:
    url: jdbc:postgresql://localhost:9010/vibe_coding_db
    username: user
    password: pass
    driver-class-name: org.postgresql.Driver

# JPA/Hibernate Configurations:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

# Gemini-AI Configurations:
  ai:
    google:
      genai:
        api-key: ${GOOGLE_GENAI_APIKEY}
        chat:
          options:
            model: gemini-3-flash-preview
            temperature: 0.0

# JWT Configurations:
jwt:
  secret-key: ${JWT_SECRET}

# Stripe Payment Integration Configurations:
stripe:
  api:
    secret: ${STRIPE_API_SECRET}
  webhook:
    secret: ${STRIPE_WEBHOOK_SECRET}

# Payment Success Redirect Url Configurations:
client:
  url: http://localhost:9090

# Port Configurations:
server:
  port: 9090

# Logging Configurations:
logging:
  level:
    org.springframework.ai:
      chat.client: DEBUG

# Minio Bucket Configurations:
minio:
  url: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin123
  project-bucket: projects